# Generated by Django 3.1.1 on 2020-10-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
