# Generated by Django 3.1.1 on 2020-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='victory',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
